name: clean_architecture
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  intl: ^0.19.0
  floor: ^1.5.0
  retrofit: ^4.1.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.2
  floor_generator: ^1.5.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
